; This file was auto-generated by drush make

api = 2
core = 7.x
; projects[drupal][version] = "7.x"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[acquia][type] = "core"
projects[acquia][download][type] = "get"
projects[acquia][download][url] = "http://www.acquia.com/downloads/3164156/full/tar.gz"

projects[adaptive_image][version] = "1.4"

projects[advanced_help][version] = "1.0"

projects[auto_nodetitle][version] = "1.0"

projects[backup_migrate][version] = "2.4"

projects[bean][version] = "1.2"

projects[ctools][version] = "1.3"

projects[calendar][version] = "3.4"

projects[context][version] = "3.0-beta6"

projects[date][version] = "2.6"

projects[delta][version] = "3.0-beta11"

projects[empty_page][version] = "1.0"

projects[entity][version] = "1.1"

projects[entityreference][version] = "1.0"

projects[fast_404][version] = "1.3"

projects[features][version] = "1.0"

projects[feeds][version] = "2.0-alpha8"

projects[feeds_xpathparser][version] = "1.0-beta4"

projects[fences][version] = "1.0"

projects[field_collection][version] = "1.0-beta5"

projects[field_group][version] = "1.1"

projects[media][version] = "1.2"

projects[fontyourface][version] = "2.5"

projects[google_analytics][version] = "1.3"

projects[imce][version] = "1.6"

projects[imce_wysiwyg][version] = "1.0"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_plugin][version] = "1.0"

projects[jquery_update][version] = "2.2"

projects[libraries][version] = "2.0"

projects[link][version] = "1.0"

projects[manual-crop][version] = "1.4"

projects[memcache][version] = "1.0"

projects[menu_attributes][version] = "1.0-rc2"

projects[menu_block][version] = "2.3"

projects[menu_breadcrumb][version] = "1.3"

projects[metatags_quick][version] = "2.5"

projects[omega_tools][version] = "3.0-rc4"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[profile2][version] = "1.2"

projects[quicktabs][version] = "3.4"

projects[redirect][version] = "1.0-rc1"

projects[resp_img][version] = "1.3"

projects[revisioning][version] = "1.4"

projects[rules][version] = "2.3"

projects[save_draft][version] = "1.4"

projects[scheduler][version] = "1.0"

projects[site_map][version] = "1.0"

projects[sqlsrv][version] = "1.2"

projects[superfish][version] = "1.8"

projects[token][version] = "1.4"

projects[views][version] = "3.7"

projects[views_slideshow][version] = "3.0"

projects[webform][version] = "3.18"

projects[webform_validation][version] = "1.1"

projects[weight][version] = "2.1"

projects[wysiwyg][version] = "2.1"